; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35207.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__D8EFE972_Hello_World@cpp DB 01H
msvcjmc	ENDS
END
