; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35207.1 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__F995EC04_EndBrace@h DB 01H
__C992E0FF_Math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?add@@YAHHH@Z					; add
PUBLIC	?multiply@@YAHHH@Z				; multiply
PUBLIC	__JustMyCode_Default
EXTRN	_RTC_InitBase:PROC
EXTRN	_RTC_Shutdown:PROC
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?add@@YAHHH@Z DD imagerel $LN3
	DD	imagerel $LN3+61
	DD	imagerel $unwind$?add@@YAHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?multiply@@YAHHH@Z DD imagerel $LN3
	DD	imagerel $LN3+58
	DD	imagerel $unwind$?multiply@@YAHHH@Z
pdata	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
_RTC_Shutdown.rtc$TMZ DQ FLAT:_RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
_RTC_InitBase.rtc$IMZ DQ FLAT:_RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?multiply@@YAHHH@Z DD 025051601H
	DD	01112316H
	DD	0700a001dH
	DD	05009H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?add@@YAHHH@Z DD 025051601H
	DD	01112316H
	DD	0700a001dH
	DD	05009H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?multiply@@YAHHH@Z
_TEXT	SEGMENT
a$ = 224
b$ = 232
?multiply@@YAHHH@Z PROC					; multiply, COMDAT
; File C:\Users\91638\Desktop\Learning MF\Learning\C++\The_Cherno\HelloWorld\HelloWorld\Math.cpp
; Line 9
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__C992E0FF_Math@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
; Line 10
	mov	eax, DWORD PTR a$[rbp]
	imul	eax, DWORD PTR b$[rbp]
; Line 11
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?multiply@@YAHHH@Z ENDP					; multiply
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?add@@YAHHH@Z
_TEXT	SEGMENT
a$ = 224
b$ = 232
?add@@YAHHH@Z PROC					; add, COMDAT
; File C:\Users\91638\Desktop\Learning MF\Learning\C++\The_Cherno\HelloWorld\HelloWorld\Math.cpp
; Line 4
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	push	rdi
	sub	rsp, 232				; 000000e8H
	lea	rbp, QWORD PTR [rsp+32]
; File C:\Users\91638\Desktop\Learning MF\Learning\C++\The_Cherno\HelloWorld\HelloWorld\EndBrace.h
	lea	rcx, OFFSET FLAT:__F995EC04_EndBrace@h
	call	__CheckForDebuggerJustMyCode
	npad	1
; File C:\Users\91638\Desktop\Learning MF\Learning\C++\The_Cherno\HelloWorld\HelloWorld\Math.cpp
; Line 5
	mov	eax, DWORD PTR b$[rbp]
	mov	ecx, DWORD PTR a$[rbp]
	add	ecx, eax
	mov	eax, ecx
; File C:\Users\91638\Desktop\Learning MF\Learning\C++\The_Cherno\HelloWorld\HelloWorld\EndBrace.h
; Line 2
	lea	rsp, QWORD PTR [rbp+200]
	pop	rdi
	pop	rbp
	ret	0
?add@@YAHHH@Z ENDP					; add
_TEXT	ENDS
END
